// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SefIzFioke.Data;

#nullable disable

namespace SefIzFioke.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260607202848_DodajProfilnuSliku")]
    partial class DodajProfilnuSliku
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("SefIzFioke.Models.Komentar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReceptId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("ReceptId");

                    b.ToTable("Komentari");
                });

            modelBuilder.Entity("SefIzFioke.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("JeBlokirn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilnaSlika")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("KorisnickoIme")
                        .IsUnique();

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("SefIzFioke.Models.Recept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojPorcija")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DijetetskiRestrikcije")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DodatneSlika")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KratakOpis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NacinPripreme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Namirnice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Napomene")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sastojci")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SlikaPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VremePripreme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Recepti");
                });

            modelBuilder.Entity("SefIzFioke.Models.Upozorenje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumSlanja")
                        .HasColumnType("TEXT");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Poruka")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Upozorenja");
                });

            modelBuilder.Entity("SefIzFioke.Models.Komentar", b =>
                {
                    b.HasOne("SefIzFioke.Models.Korisnik", "Korisnik")
                        .WithMany("Komentari")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SefIzFioke.Models.Recept", "Recept")
                        .WithMany("Komentari")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Recept");
                });

            modelBuilder.Entity("SefIzFioke.Models.Recept", b =>
                {
                    b.HasOne("SefIzFioke.Models.Korisnik", "Korisnik")
                        .WithMany("Recepti")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("SefIzFioke.Models.Upozorenje", b =>
                {
                    b.HasOne("SefIzFioke.Models.Korisnik", "Korisnik")
                        .WithMany("Upozorenja")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("SefIzFioke.Models.Korisnik", b =>
                {
                    b.Navigation("Komentari");

                    b.Navigation("Recepti");

                    b.Navigation("Upozorenja");
                });

            modelBuilder.Entity("SefIzFioke.Models.Recept", b =>
                {
                    b.Navigation("Komentari");
                });
#pragma warning restore 612, 618
        }
    }
}
